# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
in
{
  "effekt-https://github.com/effekt-lang/effekt/releases/latest/download/effekt.tgz" = nodeEnv.buildNodePackage {
    name = "effekt";
    packageName = "effekt";
    version = "0.1.16";
    src = fetchurl {
      name = "effekt-0.1.16.tar.gz";
      url = https://github-releases.githubusercontent.com/245204534/2ab48880-3a19-11eb-9d35-634ad696361d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20210129%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210129T150901Z&X-Amz-Expires=300&X-Amz-Signature=9084a246004d26d1615229f748138cb6776def2f1fe3a9ec0d2de865037a158a&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=245204534&response-content-disposition=attachment%3B%20filename%3Deffekt.tgz&response-content-type=application%2Foctet-stream;
      sha256 = "3137436f3913035fbbbcddc709afe2748d2d7f994036ddb53354a4c30e0d44ec";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "A language with effects and handlers";
      homepage = "https://github.com/b-studios/effekt#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}